services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apt_backend
    restart: unless-stopped
    env_file: .env
    networks:
      - apt_ceet

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - apt_ceet

networks:
  apt_ceet:
    external: true